; Sea Dragon for GameBoy 
; Credits data
        
;------------------------------------------------------------------------------
CreditsData:
	DB	"GAMEBOY VERSION",13
	DB	"  2012 NIKITA ZIMIN",13
	DB	13
	DB	"ORIGINAL TRS-80 GAME"
	DB	"  1982 WAYNE",13
	DB	"       WESTMORELAND",13
	DB	"   AND TERRY",13
	DB	"       GILMAN",13
	DB	13
	DB	"ATARI 8-BIT VERSION "
	DB	"  1982 RUSS",13
	DB	"       WETMORE",13
	DB	13
	DB	"ZX SPECTRUM VERSION "
	DB	"  2010 ANDREY",13
	DB	"       ZHIGLOV",13
	DB	"   AND OTHERS",13
	DB	10
	DB	10,10,10,10,10,10,10,10,10,10,10,10,10,10
	DB	$ff
CreditsDataEnd:

;------------------------------------------------------------------------------
